//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Adjustment
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Adjustment()
    {
        this.AdjustmentDetails = new HashSet<AdjustmentDetail>();
    }

    public string VoucherID { get; set; }
    public string EmpID { get; set; }
    public string AdjustmentStatus { get; set; }
    public Nullable<System.DateTime> VoucherDate { get; set; }
    public string AuthorisedBySupervisor { get; set; }
    public string AuthorisedByManager { get; set; }
    public Nullable<decimal> TotalPrice { get; set; }
    public Nullable<System.DateTime> ApprovalDate { get; set; }

    public virtual Employee Employee { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<AdjustmentDetail> AdjustmentDetails { get; set; }
}

public partial class AdjustmentDetail
{
    public string AdjustmentDetailsID { get; set; }
    public string VoucherID { get; set; }
    public string ItemNumber { get; set; }
    public Nullable<int> QuantityAdjustment { get; set; }
    public string SupplierID { get; set; }
    public string Reason { get; set; }

    public virtual Adjustment Adjustment { get; set; }
    public virtual InventoryStock InventoryStock { get; set; }
    public virtual Supplier Supplier { get; set; }
}

public partial class CollectionPointDetail
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public CollectionPointDetail()
    {
        this.Departments = new HashSet<Department>();
    }

    public string CollectionPointID { get; set; }
    public string CollectionPoint { get; set; }
    public string CollectionTime { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Department> Departments { get; set; }
}

public partial class Department
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Department()
    {
        this.Disbursements = new HashSet<Disbursement>();
        this.OutstandingInfoes = new HashSet<OutstandingInfo>();
        this.Employees = new HashSet<Employee>();
    }

    public string DepartmentID { get; set; }
    public string DepartmentName { get; set; }
    public string RepID { get; set; }
    public string CollectionPointID { get; set; }

    public virtual CollectionPointDetail CollectionPointDetail { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Disbursement> Disbursements { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<OutstandingInfo> OutstandingInfoes { get; set; }
    public virtual Employee Employee { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Employee> Employees { get; set; }
}

public partial class Disbursement
{
    public string DisbursementID { get; set; }
    public string DepartmentID { get; set; }
    public string ItemNumber { get; set; }
    public Nullable<int> OrderQuantity { get; set; }
    public Nullable<int> DisbursementQuantity { get; set; }
    public string Status { get; set; }
    public string RequisitionID { get; set; }

    public virtual Department Department { get; set; }
    public virtual InventoryStock InventoryStock { get; set; }
    public virtual Requisition Requisition { get; set; }
}

public partial class Employee
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Employee()
    {
        this.Adjustments = new HashSet<Adjustment>();
        this.Departments = new HashSet<Department>();
        this.PurchaseOrders = new HashSet<PurchaseOrder>();
        this.PurchaseOrders1 = new HashSet<PurchaseOrder>();
        this.Requisitions = new HashSet<Requisition>();
    }

    public string EmpID { get; set; }
    public string DepartmentID { get; set; }
    public string EmpTitle { get; set; }
    public string EmpName { get; set; }
    public string Email { get; set; }
    public int Delegate { get; set; }
    public Nullable<System.DateTime> DelegateStartDate { get; set; }
    public Nullable<System.DateTime> DelegateEndDate { get; set; }
    public string Password { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Adjustment> Adjustments { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Department> Departments { get; set; }
    public virtual Department Department { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<PurchaseOrder> PurchaseOrders { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<PurchaseOrder> PurchaseOrders1 { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Requisition> Requisitions { get; set; }
}

public partial class InventoryStock
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public InventoryStock()
    {
        this.AdjustmentDetails = new HashSet<AdjustmentDetail>();
        this.Disbursements = new HashSet<Disbursement>();
        this.OutstandingInfoes = new HashSet<OutstandingInfo>();
        this.PurchaseOrderDetails = new HashSet<PurchaseOrderDetail>();
        this.RequisitionDetails = new HashSet<RequisitionDetail>();
    }

    public string ItemNumber { get; set; }
    public string ItemName { get; set; }
    public Nullable<int> Quantity { get; set; }
    public string ItemCategory { get; set; }
    public Nullable<int> ReorderLevel { get; set; }
    public Nullable<int> ReorderQuantity { get; set; }
    public string ItemUOM { get; set; }
    public string Bin { get; set; }
    public string Supplier1 { get; set; }
    public string Supplier2 { get; set; }
    public string Supplier3 { get; set; }
    public Nullable<decimal> Price1 { get; set; }
    public Nullable<decimal> Price2 { get; set; }
    public Nullable<decimal> Price3 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<AdjustmentDetail> AdjustmentDetails { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Disbursement> Disbursements { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<OutstandingInfo> OutstandingInfoes { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<PurchaseOrderDetail> PurchaseOrderDetails { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<RequisitionDetail> RequisitionDetails { get; set; }
}

public partial class OutstandingInfo
{
    public string OutstandingID { get; set; }
    public string ItemNumber { get; set; }
    public string DepartmentID { get; set; }
    public Nullable<int> Quantity { get; set; }
    public string Status { get; set; }
    public Nullable<int> PartialPendingQty { get; set; }

    public virtual Department Department { get; set; }
    public virtual InventoryStock InventoryStock { get; set; }
}

public partial class PurchaseOrder
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public PurchaseOrder()
    {
        this.PurchaseOrderDetails = new HashSet<PurchaseOrderDetail>();
    }

    public string POID { get; set; }
    public Nullable<System.DateTime> DeliveryDate { get; set; }
    public Nullable<System.DateTime> DateOfOrder { get; set; }
    public string RequestorID { get; set; }
    public string CommentByClerk { get; set; }
    public string ApproverID { get; set; }
    public Nullable<System.DateTime> ApprovalDate { get; set; }
    public string Status { get; set; }
    public string CommentsBySupervisor { get; set; }

    public virtual Employee Employee { get; set; }
    public virtual Employee Employee1 { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<PurchaseOrderDetail> PurchaseOrderDetails { get; set; }
}

public partial class PurchaseOrderDetail
{
    public string PODetailsID { get; set; }
    public string POID { get; set; }
    public string SupplierID { get; set; }
    public string ItemNumber { get; set; }
    public Nullable<int> Quantity { get; set; }

    public virtual InventoryStock InventoryStock { get; set; }
    public virtual PurchaseOrder PurchaseOrder { get; set; }
    public virtual Supplier Supplier { get; set; }
}

public partial class Requisition
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Requisition()
    {
        this.Disbursements = new HashSet<Disbursement>();
        this.RequisitionDetails = new HashSet<RequisitionDetail>();
    }

    public string RequisitionID { get; set; }
    public string EmpID { get; set; }
    public string CommentsByEmp { get; set; }
    public string Status { get; set; }
    public Nullable<System.DateTime> EmpRequisitionDate { get; set; }
    public Nullable<System.DateTime> ApprovalDate { get; set; }
    public string CommentsByHead { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Disbursement> Disbursements { get; set; }
    public virtual Employee Employee { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<RequisitionDetail> RequisitionDetails { get; set; }
}

public partial class RequisitionDetail
{
    public string RequisitionDetailsID { get; set; }
    public string RequisitionID { get; set; }
    public string ItemNumber { get; set; }
    public Nullable<int> ItemQuantity { get; set; }

    public virtual InventoryStock InventoryStock { get; set; }
    public virtual Requisition Requisition { get; set; }
}

public partial class Supplier
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Supplier()
    {
        this.AdjustmentDetails = new HashSet<AdjustmentDetail>();
        this.PurchaseOrderDetails = new HashSet<PurchaseOrderDetail>();
    }

    public string SupplierID { get; set; }
    public string SupplierName { get; set; }
    public string ContactName { get; set; }
    public Nullable<int> PhoneNumber { get; set; }
    public string Address { get; set; }
    public Nullable<int> Fax { get; set; }
    public string Email { get; set; }
    public string GSTRegistrationNumber { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<AdjustmentDetail> AdjustmentDetails { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<PurchaseOrderDetail> PurchaseOrderDetails { get; set; }
}

public partial class sysdiagram
{
    public string name { get; set; }
    public int principal_id { get; set; }
    public int diagram_id { get; set; }
    public Nullable<int> version { get; set; }
    public byte[] definition { get; set; }
}

public partial class View_2
{
    public string ItemNumber { get; set; }
    public Nullable<int> Quantity { get; set; }
    public string ItemCategory { get; set; }
    public Nullable<decimal> Price3 { get; set; }
    public Nullable<decimal> Price2 { get; set; }
    public Nullable<decimal> Price1 { get; set; }
    public string Supplier3 { get; set; }
    public string Supplier2 { get; set; }
    public string Supplier1 { get; set; }
    public string POID { get; set; }
    public Nullable<System.DateTime> ApprovalDate { get; set; }
    public string Status { get; set; }
    public string Expr1 { get; set; }
    public string SupplierID { get; set; }
    public string Expr2 { get; set; }
    public Nullable<int> Expr3 { get; set; }
}

public partial class spGetItemsByCategory_Result
{
    public string ItemName { get; set; }
    public string ItemCategory { get; set; }
}

public partial class spGetSupplierByItemName_Result
{
    public string ItemName { get; set; }
    public string Supplier1 { get; set; }
    public string Supplier2 { get; set; }
    public string Supplier3 { get; set; }
}

public partial class spGetUOMForItem_Result
{
    public string ItemUOM { get; set; }
    public string ItemName { get; set; }
}

public partial class spPurchaseOrderList_Result
{
    public string POID { get; set; }
    public Nullable<System.DateTime> DeliveryDate { get; set; }
    public string SupplierName { get; set; }
    public Nullable<System.DateTime> DateOfOrder { get; set; }
    public string Status { get; set; }
}
