package com.example.joash.ad;

import android.content.Intent;
import android.os.AsyncTask;
import android.os.Bundle;
import android.support.v7.app.AppCompatActivity;
import android.view.Menu;
import android.view.MenuItem;
import android.view.View;
import android.widget.AdapterView;
import android.widget.ListView;
import android.widget.SimpleAdapter;
import android.widget.Toast;
import java.util.List;


//Starting Activity for Supervisor


public class SupervisorActivity  extends AppCompatActivity implements AdapterView.OnItemClickListener  {


    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_supervisor);
        setTitle("Purchase Order List");


        final ListView l=(ListView)findViewById(R.id.listviewsp);


        //To get the List of Purchase Orders generated by Clerk


        new AsyncTask<String, Void, List<PurchaseOrder>>() {
            @Override
            protected List<PurchaseOrder> doInBackground(String... params) {
                return PurchaseOrder.jread();
            }

            @Override
            protected void onPostExecute(List<PurchaseOrder> result) {

                l.setAdapter(new SimpleAdapter(getApplicationContext(),
                        result,R.layout.suprow, new String[]{"PONumber", "GeneratedBy"},
                        new int[]{ R.id.Text1, R.id.Text2}));

            }}.execute();
        l.setOnItemClickListener(this);
    }



    //OnClick Event for the List of Purchase Orders


    @Override
    public void onItemClick(AdapterView<?> av, View v,
                                   int position, long id) {
        PurchaseOrder po = (PurchaseOrder)  av.getAdapter().getItem(position);
        Intent i = new Intent(SupervisorActivity.this,POActivity.class);
        i.putExtra("PO",po);
        startActivity(i);
    }


    //Menu Options for Supervisor

    @Override
    public boolean onCreateOptionsMenu(Menu menu) {
        getMenuInflater().inflate(R.menu.menu, menu);
        return true;
    }



    //Onclick Options for the Menu


    @Override
    public boolean onOptionsItemSelected(MenuItem item) {
        switch (item.getItemId()) {

            case R.id.Logout:
                Intent k = new Intent(this, MainActivity.class);
                Toast.makeText(this, "Successfully Logged Out", Toast.LENGTH_SHORT).show();
                startActivity(k);

            default:
                return super.onOptionsItemSelected(item);

        }

    }

}
