//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class OutstandingInfo
    {
        public string OutstandingID { get; set; }
        public string ItemNumber { get; set; }
        public string DepartmentID { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string Status { get; set; }
        public Nullable<int> PartialPendingQty { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual InventoryStock InventoryStock { get; set; }
    }
}
