//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseOrderDetail
    {
        public string PODetailsID { get; set; }
        public string POID { get; set; }
        public string SupplierID { get; set; }
        public string ItemNumber { get; set; }
        public Nullable<int> Quantity { get; set; }
    
        public virtual InventoryStock InventoryStock { get; set; }
        public virtual PurchaseOrder PurchaseOrder { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
