//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_2
    {
        public string ItemNumber { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string ItemCategory { get; set; }
        public Nullable<decimal> Price3 { get; set; }
        public Nullable<decimal> Price2 { get; set; }
        public Nullable<decimal> Price1 { get; set; }
        public string Supplier3 { get; set; }
        public string Supplier2 { get; set; }
        public string Supplier1 { get; set; }
        public string POID { get; set; }
        public Nullable<System.DateTime> ApprovalDate { get; set; }
        public string Status { get; set; }
        public string Expr1 { get; set; }
        public string SupplierID { get; set; }
        public string Expr2 { get; set; }
        public Nullable<int> Expr3 { get; set; }
    }
}
